spring:
  datasource:
    dynamic:
      primary: gi_test #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        gi_test:
          url: jdbc:mysql://localhost:3306/gi_test?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 246812gi
          driver-class-name: com.mysql.cj.jdbc.Driver
        njds_warehouse:
          url: jdbc:mysql://localhost:3306/njds_warehouse?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 246812gi
          driver-class-name: com.mysql.cj.jdbc.Driver

# 配置sql打印日志，开发环境需要，生产环境一般不需要
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

